version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    # Static config moved to traefik.yml
    # command:
    #- "--log.level=INFO"
    #- "--api.insecure=true"
    #- "--providers.docker=true"
    #- "--providers.docker.exposedbydefault=false"
    #- "--entrypoints.web.address=:80"
    ports:
      # Exposes port 80 for incoming requests
      - "80:80"
      - "443:443"
      # The Web UI port htp://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # so traefik can listen to Docker events through Docker API
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./reverse-proxy/traefik.yml:/etc/traefik/traefik.yml"
      - "./reverse-proxy/ssl-certs:/ssl-certs/certs:ro"

  server:
    image: "protected-resource-server"
    container_name: "protected-resource-server"
    labels:
      # Routers
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`protected-server.localhost`)"
      - "traefik.http.routers.server.service=server"

      # Services
      - "traefik.http.services.server.loadbalancer.server.port=5000"
      # Middlewares

