################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
  
################################################################
# Docker configuration backend
################################################################
providers:
  docker: 
    watch: true
    exposedByDefault: false
    #swarmMode: false
################################################################
# Traefik Logging
################################################################
log:
  level: INFO

################################################################
# Entrypoints
################################################################
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: default

################################################################
# SSL Certificates
################################################################
certificatesResolvers:
  default:
    acme:
      email: mlup@itu.dk
      storage: /ssl-certs/acme.json
      httpChallenge:
        entryPoint: web

